{
    "name": "GMSS Demo Suite",
    "version": "18.0.2.0.0",
    "summary": "Complete demo seed + contact enhancements + birthday campaign for temple/non-profit demo",
    "author": "i8CLOUD",
    "license": "LGPL-3",
    "category": "Demo",
    "depends": [
        "base",
        "contacts",
        "mail",
        "sale_management",
        "website",
        "website_sale",
        "appointment",
        "event",
        "account",
        "analytic",
    ],
    "data": [
        "data/analytic_plan.xml",
        "data/analytic_accounts.xml",
        "data/product_categories.xml",
        "data/products.xml",
        "data/appointment_types.xml",
        "data/event_seed.xml",
        #"data/payment_demo_provider.xml",
        "data/website_page.xml",
        "data/mail_template.xml",
        "data/ir_cron.xml",
        "security/ir.model.access.csv",
        "views/res_partner_views.xml",
        "views/event_templates.xml",
    ],
    "installable": True,
    "application": False,
}
